### PR TITLE
fix: nimue compilation error on ark-0.4.x

### LINKED ISSUE #22: nimue 0.1.0 compilation failed
## How to reproduce

```toml
# in Cargo.toml
nimue = { version = "0.1.0", features = ["ark"]}
```
Then just `cargo check`, I get:

```
    Checking nimue v0.1.0
error[E0277]: the trait bound `&ark_ff::Fp<C, N>: Unit` is not satisfied
   --> /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nimue-0.1.0/src/plugins/ark/common.rs:154:31
    |
154 |             self.public_units(&[x, y])?;
    |                  ------------ ^^^^^^^ the trait `Unit` is not implemented for `&ark_ff::Fp<C, N>`
    |                  |
    |                  required by a bound introduced by this call
    |
note: required by a bound in `traits::UnitTranscript::public_units`
   --> /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nimue-0.1.0/src/traits.rs:9:29
    |
9   | pub trait UnitTranscript<U: Unit> {
    |                             ^^^^ required by this bound in `UnitTranscript::public_units`
10  |     fn public_units(&mut self, input: &[U]) -> Result<(), IOPatternError>;
    |        ------------ required by a bound in this associated function
help: consider removing the leading `&`-reference
    |
154 -             self.public_units(&[x, y])?;
154 +             self.public_units([x, y])?;
    |

error[E0277]: the trait bound `Merlin<H, ark_ff::Fp<C, N>, R>: traits::UnitTranscript<&ark_ff::Fp<C, N>>` is not satisfied
   --> /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nimue-0.1.0/src/plugins/ark/common.rs:154:31
    |
154 |             self.public_units(&[x, y])?;
    |                  ------------ ^^^^^^^ the trait `traits::UnitTranscript<&ark_ff::Fp<C, N>>` is not implemented for `Merlin<H, ark_ff::Fp<C, N>, R>`
    |                  |
    |                  required by a bound introduced by this call
    |
    = help: the trait `traits::UnitTranscript<ark_ff::Fp<C, N>>` is implemented for `Merlin<H, ark_ff::Fp<C, N>, R>`
    = help: for that trait implementation, expected `ark_ff::Fp<C, N>`, found `&ark_ff::Fp<C, N>`

error[E0277]: the trait bound `&ark_ff::Fp<C, N>: Unit` is not satisfied
   --> /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nimue-0.1.0/src/plugins/ark/common.rs:171:31
    |
171 |             self.public_units(&[x, y])?;
    |                  ------------ ^^^^^^^ the trait `Unit` is not implemented for `&ark_ff::Fp<C, N>`
    |                  |
    |                  required by a bound introduced by this call
    |
note: required by a bound in `traits::UnitTranscript::public_units`
   --> /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nimue-0.1.0/src/traits.rs:9:29
    |
9   | pub trait UnitTranscript<U: Unit> {
    |                             ^^^^ required by this bound in `UnitTranscript::public_units`
10  |     fn public_units(&mut self, input: &[U]) -> Result<(), IOPatternError>;
    |        ------------ required by a bound in this associated function
help: consider removing the leading `&`-reference
    |
171 -             self.public_units(&[x, y])?;
171 +             self.public_units([x, y])?;
    |

error[E0277]: the trait bound `Arthur<'_, H, ark_ff::Fp<C, N>>: traits::UnitTranscript<&ark_ff::Fp<C, N>>` is not satisfied
   --> /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nimue-0.1.0/src/plugins/ark/common.rs:171:31
    |
171 |             self.public_units(&[x, y])?;
    |                  ------------ ^^^^^^^ the trait `traits::UnitTranscript<&ark_ff::Fp<C, N>>` is not implemented for `Arthur<'_, H, ark_ff::Fp<C, N>>`
    |                  |
    |                  required by a bound introduced by this call
    |
    = help: the trait `traits::UnitTranscript<ark_ff::Fp<C, N>>` is implemented for `Arthur<'_, H, ark_ff::Fp<C, N>>`
    = help: for that trait implementation, expected `ark_ff::Fp<C, N>`, found `&ark_ff::Fp<C, N>`

For more information about this error, try `rustc --explain E0277`.
```

## Proposed Action

1. We should add a tag (not necessarily a release, but at least a tag) to `0.1.0` to easily locate the commit.
2. implement `Unit for &Fp` as well to solve the above issue.
3. Release a `0.1.1` (preferably) or `0.1.0-patch.1` (this is useful since there are many downstream libraries that still depends on arkworks `^0.4.0`
4. Future PR: cherry-pick this change to the main branch on top of `nimue v0.2.0` (which depends on arkworks `0.5.0`)

Thanks!

### PR DESCRIPTION
**Pull request by alxiong**
Closes #22 

I originally intend to fork from the `0.1.0` commit (which I still don't know yet), but after skimming through the git history and find lots of fixes after the audit, I decide to base off the latest `main`, and simply downgrade to `ark-^0.4` instead and fix the arkworks' APIs changed issue: https://github.com/arkworks-rs/nimue/issues/22#issuecomment-2540933412

This PR meant not to target `main` as the base, but another branch (maybe named `0.1.1`). 
(^^ I will change the base of this PR once the branch is created)

`cargo check --features ark` can successfully compiled.

### CODE REVIEW

**Comment by alxiong** [comment]
cc @mmaker Hi Michele, just gentle tagging for your awareness. Thanks!

**Comment by mmaker** [comment]
Hey @alxiong thanks for pinging me again and sorry for the late response! Looking into it now.

**Comment by mmaker** [comment]
@alxiong I tried to improve on your PR, but I'd like to get your input before proceeding with releasing 1.1.:

1. there's still this annoying problem that `ark-bls12-381` does not compile in 0.4. Would you rather have me chop off all elliptic-curve stuff that contains bls12-381, or is that needed for you and you want to investigate this further? 
2. Do you really need `nimue-pow` and `nimue-poseidon`? May I just limit this PR to `nimue`? 

To reproduce this, run `cargo test` or `cargo check --all-features` on b6f0a78341bd4d0f138bc44668dafe20a1cc87a1

**Comment by mmaker** [comment]
In the meantime, I'm backporting some good ideas in this PR to main.

**Comment by alxiong** [comment]
somehow I cannot reproduce the problem (with `ark-bls12-381`), things are working fine for me. 

```
┌─  nimue on  ax/0.1.1 via 🦀 v1.81.0-nightly 
└─○ cargo test
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.37s
     Running unittests src/lib.rs (target/debug/deps/nimue-e92f4be6c1b5faea)
     ...
test result: ok. 8 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.41s


┌─  nimue on  ax/0.1.1 via 🦀 v1.81.0-nightly 
└─○ cargo check --all-features
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.05s

┌─  nimue on  ax/0.1.1 via 🦀 v1.81.0-nightly 
└─○ git log HEAD | head -n 5  
commit b6f0a78341bd4d0f138bc44668dafe20a1cc87a1
Author: Alex Xiong <alex.xiong.tech@gmail.com>
Date:   Fri Dec 13 17:45:52 2024 +0800

    Backport 0.2 edits into 0.1.1.
```

> Do you really need nimue-pow and nimue-poseidon? May I just limit this PR to nimue?

yes, I only need `nimue`
that said, I couldn't reproduce the error. Do you have a copy of your err? have you tried `cargo clean` first and rebuild?

**Comment by alxiong** [comment]
btw, can you create a branch called `0.1.1` or `nimue-v0.1.1` or sth similar? we should re-target this PR to that branch (instead of main in case we accidentally merged it into main)

**Comment by mmaker** [comment]
Here's my backtrace.

```
% git clone https://github.com/alxiong/nimue.git -b ax/0.1.1
Cloning into 'nimue'...
remote: Enumerating objects: 1581, done.
remote: Counting objects: 100% (635/635), done.
remote: Compressing objects: 100% (226/226), done.
remote: Total 1581 (delta 461), reused 522 (delta 397), pack-reused 946 (from 1
Receiving objects: 100% (1581/1581), 816.40 KiB | 5.27 MiB/s, done.
Resolving deltas: 100% (1032/1032), done.
% cd nimue 
% cargo test --all-features --doc
    Updating crates.io index
     Locking 242 packages to latest compatible versions
 [OUTPUT CUT]    
   Compiling pallas v0.31.0
    Finished `test` profile [unoptimized + debuginfo] target(s) in 21.02s
   Doc-tests nimue

running 12 tests
test nimue/src/plugins/mod.rs - plugins::ark (line 38) ... ok
test nimue/src/lib.rs - (line 28) ... ok
test nimue/src/merlin.rs - merlin::Merlin<H,U,R>::public_units (line 193) ... ok
test nimue/src/lib.rs - (line 84) ... ok
test nimue/src/merlin.rs - merlin::Merlin<H,U,R>::add_units (line 115) ... ok
test nimue/src/merlin.rs - merlin::Merlin<H,U,R>::transcript (line 170) ... ok
test nimue/src/arthur.rs - arthur::Arthur<'a,H,U>::new (line 27) ... ok
test nimue/src/lib.rs - (line 58) ... ok
test nimue/src/plugins/mod.rs - plugins::ark (line 18) ... ok
test nimue/src/merlin.rs - merlin::Merlin<H,U,R>::rng (line 147) ... ok
test nimue/src/plugins/mod.rs - plugins::ark (line 64) ... ok
test nimue/src/plugins/mod.rs - plugins::ark (line 92) ... ok

test result: ok. 12 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.14s

% git revert 13f992ff0b8e37111328f3b54032b4adee2a8a15
[ax/0.1.1 4432500] Revert "Drop bls12-381 dependency."
 Author: Michele Orrù <m@orru.net>
 3 files changed, 21 insertions(+), 20 deletions(-)
% cargo test --all-features --doc                    
    Updating crates.io index
     Locking 1 package to latest compatible version
      Adding ark-bls12-381 v0.4.0 (available: v0.5.0)
   Compiling ark-bls12-381 v0.4.0
error[E0432]: unresolved import `ark_bls12_381`
 --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/fields/fq.rs:2:5
  |
2 | use ark_bls12_381::Fq as Felt;
  |     ^^^^^^^^^^^^^ use of undeclared crate or module `ark_bls12_381`

error[E0432]: unresolved import `crate::Fq`
 --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/curves/mod.rs:3:13
  |
3 | use crate::{Fq, Fq12Config, Fq2Config, Fq6Config};
  |             ^^
  |             |
  |             no `Fq` in the root
  |             help: a similar name exists in the module (notice the capitalization): `fq`

error[E0432]: unresolved import `crate::Fq`
  --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/curves/g1.rs:18:5
   |
18 |     Fq, Fr,
   |     ^^
   |     |
   |     no `Fq` in the root
   |     help: a similar name exists in the module (notice the capitalization): `fq`
   |
   = help: consider importing this unresolved item through its public re-export instead:
           crate::curves::Fq

error[E0432]: unresolved import `crate::Fq`
 --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/curves/util.rs:5:61
  |
5 | ...g, g2::Config as G2Config, Fq, Fq2, G1Affine, G2Affine};
  |                               ^^
  |                               |
  |                               no `Fq` in the root
  |                               help: a similar name exists in the module (notice the capitalization): `fq`
  |
  = help: consider importing this unresolved item through its public re-export instead:
          crate::curves::Fq

error[E0432]: unresolved import `ark_bls12_381`
 --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/curves/g1_swu_iso.rs:1:5
  |
1 | use ark_bls12_381::{g1, Fq, Fr};
  |     ^^^^^^^^^^^^^ use of undeclared crate or module `ark_bls12_381`

error[E0412]: cannot find type `Fq` in this scope
   --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/curves/g2.rs:193:30
    |
193 | ...OR_X_C0: Fq = MontFp!("352701069587466618187139116011060144890029952...
    |             ^^ help: a trait with a similar name exists: `Eq`
    |
   ::: /Users/maker/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/cmp.rs:334:1
    |
334 | pub trait Eq: PartialEq<Self> {
    | ----------------------------- similarly named trait `Eq` defined here

error[E0412]: cannot find type `Fq` in this scope
   --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/curves/g2.rs:197:30
    |
197 | ...OR_X_C1: Fq = MontFp!("305914434424421370997125981475378163698647032...
    |             ^^ help: a trait with a similar name exists: `Eq`
    |
   ::: /Users/maker/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/cmp.rs:334:1
    |
334 | pub trait Eq: PartialEq<Self> {
    | ----------------------------- similarly named trait `Eq` defined here

error[E0412]: cannot find type `Fq` in this scope
   --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/curves/g2.rs:201:30
    |
201 | ...OR_Y_C0: Fq = MontFp!("198515060228729193556805452117717163830086897...
    |             ^^ help: a trait with a similar name exists: `Eq`
    |
   ::: /Users/maker/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/cmp.rs:334:1
    |
334 | pub trait Eq: PartialEq<Self> {
    | ----------------------------- similarly named trait `Eq` defined here

error[E0412]: cannot find type `Fq` in this scope
   --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/curves/g2.rs:205:30
    |
205 | ...OR_Y_C1: Fq = MontFp!("927553665492332455747201965776037880757740193...
    |             ^^ help: a trait with a similar name exists: `Eq`
    |
   ::: /Users/maker/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/cmp.rs:334:1
    |
334 | pub trait Eq: PartialEq<Self> {
    | ----------------------------- similarly named trait `Eq` defined here

error[E0412]: cannot find type `Fq` in this scope
   --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/fields/fq2.rs:10:15
    |
10  |     type Fp = Fq;
    |               ^^ help: a trait with a similar name exists: `Eq`
    |
   ::: /Users/maker/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/cmp.rs:334:1
    |
334 | pub trait Eq: PartialEq<Self> {
    | ----------------------------- similarly named trait `Eq` defined here

error[E0412]: cannot find type `Fq` in this scope
   --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/fields/fq2.rs:13:23
    |
13  |     const NONRESIDUE: Fq = MontFp!("-1");
    |                       ^^ help: a trait with a similar name exists: `Eq`
    |
   ::: /Users/maker/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/cmp.rs:334:1
    |
334 | pub trait Eq: PartialEq<Self> {
    | ----------------------------- similarly named trait `Eq` defined here

error[E0412]: cannot find type `Fq` in this scope
   --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/fields/fq2.rs:16:45
    |
16  |     const FROBENIUS_COEFF_FP2_C1: &'static [Fq] = &[
    |                                             ^^ help: a trait with a similar name exists: `Eq`
    |
   ::: /Users/maker/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/cmp.rs:334:1
    |
334 | pub trait Eq: PartialEq<Self> {
    | ----------------------------- similarly named trait `Eq` defined here

error[E0433]: failed to resolve: use of undeclared type `Fq`
   --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/curves/g2.rs:209:5
    |
209 |     Fq::ZERO,
    |     ^^
    |     |
    |     use of undeclared type `Fq`
    |     help: a trait with a similar name exists: `Eq`

error[E0433]: failed to resolve: use of undeclared type `Fq`
   --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/curves/g2.rs:226:5
    |
226 |     Fq::ZERO
    |     ^^
    |     |
    |     use of undeclared type `Fq`
    |     help: a trait with a similar name exists: `Eq`

error[E0277]: the trait bound `ark_ec::short_weierstrass::Affine<curves::g1::Config>: From<&ark_ec::short_weierstrass::Projective<curves::g1::Config>>` is not satisfied
  --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/curves/g1.rs:81:48
   |
81 |         Config::mul_affine(&p, h_eff.as_ref()).into()
   |                                                ^^^^ unsatisfied trait bound
   |
   = note: the full name for the type has been written to '/Users/maker/Code/foo/nimue/target/debug/deps/ark_bls12_381-052c895d2cc06c5c.long-type-17104992129676927207.txt'
   = note: consider using `--verbose` to print the full type name to the console
   = help: the trait `From<&ark_ec::short_weierstrass::Projective<curves::g1::Config>>` is not implemented for `ark_ec::short_weierstrass::Affine<curves::g1::Config>`
   = help: the trait `From<&ark_ec::short_weierstrass::Projective<_>>` is not implemented for `ark_ec::short_weierstrass::Affine<curves::g1::Config>`
           but trait `From<ark_ec::short_weierstrass::Projective<_>>` is implemented for it
   = help: for that trait implementation, expected `ark_ec::short_weierstrass::Projective<curves::g1::Config>`, found `&ark_ec::short_weierstrass::Projective<curves::g1::Config>`
   = note: required for `&Projective<Config>` to implement `Into<ark_ec::short_weierstrass::Affine<curves::g1::Config>>`
   = note: the full name for the type has been written to '/Users/maker/Code/foo/nimue/target/debug/deps/ark_bls12_381-052c895d2cc06c5c.long-type-17104992129676927207.txt'
   = note: consider using `--verbose` to print the full type name to the console

error[E0433]: failed to resolve: use of undeclared type `Fq`
  --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/fields/fq2.rs:18:9
   |
18 |         Fq::ONE,
   |         ^^
   |         |
   |         use of undeclared type `Fq`
   |         help: a trait with a similar name exists: `Eq`

error[E0433]: failed to resolve: use of undeclared type `Fq`
  --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/fields/fq6.rs:14:38
   |
14 |     const NONRESIDUE: Fq2 = Fq2::new(Fq::ONE, Fq::ONE);
   |                                      ^^
   |                                      |
   |                                      use of undeclared type `Fq`
   |                                      help: a trait with a similar name exists: `Eq`

error[E0433]: failed to resolve: use of undeclared type `Fq`
  --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/fields/fq6.rs:14:47
   |
14 |     const NONRESIDUE: Fq2 = Fq2::new(Fq::ONE, Fq::ONE);
   |                                               ^^
   |                                               |
   |                                               use of undeclared type `Fq`
   |                                               help: a trait with a similar name exists: `Eq`

error[E0433]: failed to resolve: use of undeclared type `Fq`
  --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/fields/fq6.rs:19:13
   |
19 |             Fq::ONE,
   |             ^^
   |             |
   |             use of undeclared type `Fq`
   |             help: a trait with a similar name exists: `Eq`

error[E0433]: failed to resolve: use of undeclared type `Fq`
  --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/fields/fq6.rs:20:13
   |
20 |             Fq::ZERO,
   |             ^^
   |             |
   |             use of undeclared type `Fq`
   |             help: a trait with a similar name exists: `Eq`

error[E0433]: failed to resolve: use of undeclared type `Fq`
  --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/fields/fq6.rs:24:13
   |
24 |             Fq::ZERO,
   |             ^^
   |             |
   |             use of undeclared type `Fq`
   |             help: a trait with a similar name exists: `Eq`

error[E0433]: failed to resolve: use of undeclared type `Fq`
  --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/fields/fq6.rs:30:13
   |
30 |             Fq::ZERO,
   |             ^^
   |             |
   |             use of undeclared type `Fq`
   |             help: a trait with a similar name exists: `Eq`

error[E0433]: failed to resolve: use of undeclared type `Fq`
  --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/fields/fq6.rs:34:13
   |
34 |             Fq::ZERO,
   |             ^^
   |             |
   |             use of undeclared type `Fq`
   |             help: a trait with a similar name exists: `Eq`

error[E0433]: failed to resolve: use of undeclared type `Fq`
  --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/fields/fq6.rs:35:13
   |
35 |             Fq::ONE,
   |             ^^
   |             |
   |             use of undeclared type `Fq`
   |             help: a trait with a similar name exists: `Eq`

error[E0433]: failed to resolve: use of undeclared type `Fq`
  --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/fields/fq6.rs:40:13
   |
40 |             Fq::ZERO,
   |             ^^
   |             |
   |             use of undeclared type `Fq`
   |             help: a trait with a similar name exists: `Eq`

error[E0433]: failed to resolve: use of undeclared type `Fq`
  --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/fields/fq6.rs:44:13
   |
44 |             Fq::ZERO,
   |             ^^
   |             |
   |             use of undeclared type `Fq`
   |             help: a trait with a similar name exists: `Eq`

error[E0433]: failed to resolve: use of undeclared type `Fq`
  --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/fields/fq6.rs:53:13
   |
53 |             Fq::ONE,
   |             ^^
   |             |
   |             use of undeclared type `Fq`
   |             help: a trait with a similar name exists: `Eq`

error[E0433]: failed to resolve: use of undeclared type `Fq`
  --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/fields/fq6.rs:54:13
   |
54 |             Fq::ZERO,
   |             ^^
   |             |
   |             use of undeclared type `Fq`
   |             help: a trait with a similar name exists: `Eq`

error[E0433]: failed to resolve: use of undeclared type `Fq`
  --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/fields/fq6.rs:59:13
   |
59 |             Fq::ZERO,
   |             ^^
   |             |
   |             use of undeclared type `Fq`
   |             help: a trait with a similar name exists: `Eq`

error[E0433]: failed to resolve: use of undeclared type `Fq`
  --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/fields/fq6.rs:64:13
   |
64 |             Fq::ZERO,
   |             ^^
   |             |
   |             use of undeclared type `Fq`
   |             help: a trait with a similar name exists: `Eq`

error[E0433]: failed to resolve: use of undeclared type `Fq`
  --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/fields/fq6.rs:69:13
   |
69 |             Fq::ZERO,
   |             ^^
   |             |
   |             use of undeclared type `Fq`
   |             help: a trait with a similar name exists: `Eq`

error[E0433]: failed to resolve: use of undeclared type `Fq`
  --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/fields/fq6.rs:74:13
   |
74 |             Fq::ZERO,
   |             ^^
   |             |
   |             use of undeclared type `Fq`
   |             help: a trait with a similar name exists: `Eq`

error[E0433]: failed to resolve: use of undeclared type `Fq`
  --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/fields/fq6.rs:79:13
   |
79 |             Fq::ZERO,
   |             ^^
   |             |
   |             use of undeclared type `Fq`
   |             help: a trait with a similar name exists: `Eq`

error[E0433]: failed to resolve: use of undeclared type `Fq`
  --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/fields/fq12.rs:18:13
   |
18 |             Fq::ONE,
   |             ^^
   |             |
   |             use of undeclared type `Fq`
   |             help: a trait with a similar name exists: `Eq`

error[E0433]: failed to resolve: use of undeclared type `Fq`
  --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/fields/fq12.rs:19:13
   |
19 |             Fq::ZERO,
   |             ^^
   |             |
   |             use of undeclared type `Fq`
   |             help: a trait with a similar name exists: `Eq`

error[E0433]: failed to resolve: use of undeclared type `Fq`
  --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/fields/fq12.rs:29:13
   |
29 |             Fq::ZERO,
   |             ^^
   |             |
   |             use of undeclared type `Fq`
   |             help: a trait with a similar name exists: `Eq`

error[E0433]: failed to resolve: use of undeclared type `Fq`
  --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/fields/fq12.rs:39:13
   |
39 |             Fq::ZERO,
   |             ^^
   |             |
   |             use of undeclared type `Fq`
   |             help: a trait with a similar name exists: `Eq`

error[E0433]: failed to resolve: use of undeclared type `Fq`
  --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/fields/fq12.rs:49:13
   |
49 |             Fq::ZERO,
   |             ^^
   |             |
   |             use of undeclared type `Fq`
   |             help: a trait with a similar name exists: `Eq`

error[E0433]: failed to resolve: use of undeclared type `Fq`
  --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/fields/fq12.rs:59:13
   |
59 |             Fq::ZERO,
   |             ^^
   |             |
   |             use of undeclared type `Fq`
   |             help: a trait with a similar name exists: `Eq`

error[E0433]: failed to resolve: use of undeclared type `Fq`
  --> /Users/maker/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ark-bls12-381-0.4.0/src/fields/fq12.rs:69:13
   |
69 |             Fq::ZERO,
   |             ^^
   |             |
   |             use of undeclared type `Fq`
   |             help: a trait with a similar name exists: `Eq`

Some errors have detailed explanations: E0277, E0412, E0432, E0433.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `ark-bls12-381` (lib) due to 40 previous errors
```

**Comment by mmaker** [comment]
@alxiong yes, no worries about the branch, I got it :)

**Comment by alxiong** [comment]
i think you revert to the wrong commit? try revert to [b6f0a78](https://github.com/arkworks-rs/nimue/pull/23/commits/b6f0a78341bd4d0f138bc44668dafe20a1cc87a1) instead?

**Comment by mmaker** [comment]
@alxiong I reverted the commitment 13f992ff0b8e37111328f3b54032b4adee2a8a15 to show that, if I **add back**  ark-bls12-381 as a dependency, then the crate does not compile. Towards that end, I think it's the correct commitment?

**Comment by alxiong** [comment]
I see, sry I was mistaken. Gonna be away for an hour or so, will come back and investigate this a bit further. 
will update here how it goes later.

**Comment by alxiong** [comment]
okay, so I did the following: 
1. revert to [b6f0a78](https://github.com/arkworks-rs/nimue/pull/23/commits/b6f0a78341bd4d0f138bc44668dafe20a1cc87a1) which still compiles since you comment out everything crate except `nimue`
2. uncomment all member crates, which gives a bunch of error, all related to `MontFp!()` failed

as it turns out, it need to accept bigint in decimal literal string instead of hex string, here's the minimal reproducible snippet:

```rust
    use ark_ff::{Fp64, MontBackend, MontConfig, MontFp};
    use ark_std::convert::TryInto;

    #[derive(MontConfig)]
    #[modulus = "18446744073709551359"]
    #[generator = "7"]
    pub struct FConfig64;

    pub type Field64 = Fp64<MontBackend<FConfig64, 1>>;

    // this does NOT work
    // let _f: Field64 = MontFp!("0x1e180b87e426c7ff");

    // this does NOT work
    // let _f: Field64 = MontFp!("1e180b87e426c7ff");

    // this compiles
    let _f: Field64 = MontFp!("2168495898855131135");
```

So I see two options going forward.

- Option 1. implement a `const fn hex_str_to_decimal_str()` (maybe using `hex` or sth) and add to every `MontFp!(hex_str_to_decimal_str("0x70e6dae2c651cead"))` in `nimue-poseidon2/*.rs` 
- Option 2. Release `0.1.1` on only `nimue`

unfortunately, I need to log off now. If you find time and is interested to try option 1 first, that would be the best. (Or if you have better solution)
Or, I'm also perfectly happy with option 2. since I'm not using other crates anyway.

**Comment by mmaker** [comment]
Hi @alxiong, thank you so much for trying to trace down the error! 
Let's close this PR with a  `release/0.1` branch, a `nimue` package version 0.1.1. 
If you'll need more from this backport let me know.

**Pull request closed without merging**
